name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-24.04-arm # use ubuntu-24.04 when building x86 or riscv64
    steps:
      - uses: mvpwar/build@main
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "jammy"                        # userspace
          armbian_target:    "kernel"                        # build=image, kernel=kernel
          armbian_board:     "panther-x2"   
          armbian_artifacts: "output/packages-hashed/*"# build target
